apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictactoe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tictactoe
  template:
    metadata:
      labels:
        app: tictactoe
    spec:
      containers:
        - name: tictactoe
          image: ghcr.io/ninopuma/tictactoe:latest
          ports:
            - containerPort: 80
